var is_num = 9;
console.log("is_num > 9? I predict False");
console.log(is_num > 9);
console.log("is_num < 3? I predict False ");
console.log(is_num < 3);
console.log("is_num <= 5? I predict False ");
console.log(is_num <= 5);
console.log("is_num >=10? I predict False");
console.log(is_num >= 10);
console.log("is_num  == 20? I predict False");
console.log(is_num == 20);
console.log("is_num == 9, ? I predict True");
console.log(is_num == 9);
console.log("is_num >= 9? I predict True");
console.log(is_num >= 9);
console.log("is_num <= 9? I predict True");
console.log(is_num <= 9);
console.log("is_num > 1? I predict True");
console.log(is_num > 1);
console.log("is_num < 10? I predict True");
console.log(is_num < 10);
